from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

nikita = InlineKeyboardMarkup(row_width=2)
timur = InlineKeyboardMarkup(row_width=2)
bagir = InlineKeyboardMarkup(row_width=2)
andrey = InlineKeyboardMarkup(row_width=2)
gabib = InlineKeyboardMarkup(row_width=2)
vova = InlineKeyboardMarkup(row_width=2)
wolfs = InlineKeyboardMarkup(row_width=2)
azers = InlineKeyboardMarkup(row_width=2)

yes_nikita_btn = InlineKeyboardButton(text='Да', callback_data='yes_nikita_btn')
no_nikita_btn = InlineKeyboardButton(text='Нет', callback_data='no_nikita_btn')
yes_timur_btn = InlineKeyboardButton(text='Да', callback_data='yes_timur_btn')
no_tumur_btn = InlineKeyboardButton(text='Нет', callback_data='no_timur_btn')
yes_bagir_btn = InlineKeyboardButton(text='Да', callback_data='yes_bagir_btn')
no_bagir_btn = InlineKeyboardButton(text='Нет', callback_data='no_bagir_btn')
yes_andrey_btn = InlineKeyboardButton(text='Да', callback_data='yes_andrey_btn')
no_andrey_btn = InlineKeyboardButton(text='Нет', callback_data='no_andrey_btn')
yes_gabib_btn = InlineKeyboardButton(text='Да', callback_data='yes_gabib_btn')
no_gabib_btn = InlineKeyboardButton(text='Нет', callback_data='no_gabib_btn')
yes_vova_btn = InlineKeyboardButton(text='Да', callback_data='yes_vova_btn')
no_vova_btn = InlineKeyboardButton(text='Нет', callback_data='no_vova_btn')
yes_wolfs_btn = InlineKeyboardButton(text='Да', callback_data='yes_wolfs_btn')
no_wolfs_btn = InlineKeyboardButton(text='Нет', callback_data='no_wolfs_btn')
yes_azers_btn = InlineKeyboardButton(text='Да', callback_data='yes_azers_btn')
no_azers_btn = InlineKeyboardButton(text='Нет', callback_data='no_azers_btn')

nikita.row(yes_nikita_btn, no_nikita_btn)
timur.row(yes_timur_btn, no_tumur_btn)
bagir.row(yes_bagir_btn, no_bagir_btn)
andrey.row(yes_andrey_btn, no_andrey_btn)
gabib.row(yes_gabib_btn, no_gabib_btn)
vova.row(yes_vova_btn, no_vova_btn)
wolfs.row(yes_wolfs_btn, no_wolfs_btn)
azers.row(yes_azers_btn, no_azers_btn)
